[package]
name = "caparking_lib"
version = "0.1.0"
authors = []
edition = "2021"


[lib]
path = "src/lib.rs"


[dependencies]
log = "0.4.14"
serde = "1.0.127"
serde_json = "1.0.66"
chrono = {version = "0.4.19", features = ["serde"]}
